version: '3'
volumes:
  postgres_volume:

services:
  # This is here for your reference if you ever want to run backend in the container (remember to change POSTGRES_HOST in .env file)
  # backend:
  #   container_name: instagram-backend
  #   build:
  #     context: .
  #   volumes:
  #   - .:/app
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   command: >
  #     bash -c "python instagram-backend/manage.py collectstatic --noinput &&
  #              python instagram-backend/manage.py migrate &&
  #              python instagram-backend/manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: instagram-frontend
    image: konradgalczynski07/ig-frontend:latest
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      
  postgres:
    container_name: instagram-postgres
    image: postgres:11
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
