version: '3'
volumes:
  postgres_volume:

services:
  backend:
    container_name: instagram-backend
    build:
      context: .
    volumes:
    - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      bash -c "python instagram-backend/manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: instagram-frontend
    image: konradgalczynski07/ig-frontend:latest
    ports:
      - "3000:3000"
      
  postgres:
    container_name: instagram-postgres
    image: postgres:11
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
